/*
 * This file is part of Mixin, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.asm.util;

import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldNode;

/**
 * Utilities for detecting Kotlin-compiled classes and the compiler-generated
 * artefacts they contain. Kotlin mixins are supported natively by Mixin, but
 * the Kotlin compiler emits members which are illegal in a mixin written in
 * Java, for example the {@code Companion} field generated for companion
 * objects or the static methods generated for {@code @JvmStatic} members.
 * These artefacts are transparently renamed by the transformer so that
 * Kotlin mixins behave the same as Java mixins.
 */
public final class KotlinUtil {

    /**
     * Descriptor of the {@code kotlin.Metadata} annotation which the Kotlin
     * compiler writes to every Kotlin class. Its presence is a reliable
     * indicator that a class was compiled from Kotlin source.
     */
    public static final String KOTLIN_METADATA = "Lkotlin/Metadata;";

    /**
     * Prefix for descriptors of all annotations in the {@code kotlin} package,
     * for example {@code kotlin.Metadata} or {@code kotlin.jvm.JvmName}.
     */
    public static final String KOTLIN_ANNOTATION_PREFIX = "Lkotlin/";

    /**
     * Name of the static field generated by the Kotlin compiler to hold the
     * singleton instance of a companion object.
     */
    public static final String COMPANION_FIELD = "Companion";

    /**
     * Name of the static field generated by the Kotlin compiler to hold the
     * singleton instance of an {@code object} declaration.
     */
    public static final String INSTANCE_FIELD = "INSTANCE";

    /**
     * Suffix of the helper class generated by the Kotlin compiler for
     * non-abstract interface methods when compiling with legacy
     * {@code -Xjvm-default} compatibility modes.
     */
    public static final String DEFAULT_IMPLS_SUFFIX = "$DefaultImpls";

    private KotlinUtil() {
        // Utility class
    }

    /**
     * Determine whether the supplied class node was compiled from Kotlin
     * source, by looking for the {@code kotlin.Metadata} annotation which
     * the Kotlin compiler writes to every class.
     *
     * @param classNode class to inspect
     * @return true if the class was compiled from Kotlin
     */
    public static boolean isKotlinClass(ClassNode classNode) {
        if (classNode == null) {
            return false;
        }
        return Annotations.get(classNode.visibleAnnotations, KotlinUtil.KOTLIN_METADATA) != null
                || Annotations.get(classNode.invisibleAnnotations, KotlinUtil.KOTLIN_METADATA) != null;
    }

    /**
     * Determine whether the supplied annotation descriptor belongs to the
     * {@code kotlin} package, for example {@code kotlin.Metadata} or
     * {@code kotlin.jvm.JvmStatic}. These annotations describe how the
     * mixin was compiled and must never be merged into target classes.
     *
     * @param desc annotation descriptor
     * @return true if the annotation is a Kotlin annotation
     */
    public static boolean isKotlinAnnotation(String desc) {
        return desc != null && desc.startsWith(KotlinUtil.KOTLIN_ANNOTATION_PREFIX);
    }

    /**
     * Determine whether the supplied field is the {@code Companion} field
     * generated by the Kotlin compiler for a companion object.
     *
     * @param field field to inspect
     * @return true if the field is a companion object reference
     */
    public static boolean isCompanionField(FieldNode field) {
        return field != null && KotlinUtil.COMPANION_FIELD.equals(field.name);
    }

    /**
     * Determine whether the supplied internal class name is a
     * {@code DefaultImpls} helper class generated by the Kotlin compiler
     * for interface mixins compiled with legacy {@code -Xjvm-default}
     * compatibility modes.
     *
     * @param internalName internal (slash-separated) class name
     * @return true if the class is a DefaultImpls helper class
     */
    public static boolean isDefaultImplsClass(String internalName) {
        return internalName != null && internalName.endsWith(KotlinUtil.DEFAULT_IMPLS_SUFFIX);
    }

    /**
     * Determine whether the supplied method name is a well-known name
     * generated by the Kotlin compiler, for example {@code access$},
     * {@code copy$} or {@code $default} methods. All of these are also
     * flagged {@code ACC_SYNTHETIC} by the compiler, so they are generally
     * handled by the normal synthetic member machinery; this is used for
     * diagnostics and for tooling which needs to identify such members.
     *
     * @param name method name to inspect
     * @return true if the name looks like a Kotlin-generated method
     */
    public static boolean isKotlinSyntheticMethod(String name) {
        if (name == null) {
            return false;
        }
        return name.startsWith("access$") || name.startsWith("copy$") || name.startsWith("lambda$")
                || name.contains("$default") || name.startsWith("getWhen$");
    }

}
